Algoritmo "CALCULADORA"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/03/2022
Var
// Seção de Declarações das variáveis 
  n,c: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  escreval ("Digite un numero entre 1 a 9")
  leia (n)
  c <- 1
  enquanto (c <= 10) faca
  escreval (n, " x " ,c, " = ", n*c)
  c <- c + 1
  
  fimenquanto
Fimalgoritmo